/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3c4d00",
        "tertiary": "#000d3d",
        "primary-container": "#0d2847",
        "background": "#f7f9fb",
        "on-primary-fixed-variant": "#304868",
        "on-primary-container": "#7890b4",
        "inverse-primary": "#b0c8ef",
        "tertiary-fixed": "#dde1ff",
        "on-secondary-fixed": "#161e00",
        "outline": "#74777e",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#0038b6",
        "on-secondary-container": "#3c4d00",
        "on-tertiary-container": "#6686ff",
        "error": "#ba1a1a",
        "surface-container": "#eceef0",
        "primary": "#00132b",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-container": "#c1f100",
        "secondary-fixed-dim": "#abd600",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#c3f400",
        "primary-fixed": "#d4e3ff",
        "on-tertiary-fixed": "#001452",
        "surface-tint": "#485f81",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#b0c8ef",
        "on-primary-fixed": "#001c3a",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#5a626a",
        "surface": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#b7c4ff",
        "inverse-on-surface": "#eff1f3",
        "outline-variant": "#c4c6ce",
        "tertiary-container": "#001e6d",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "on-surface": "#0f172a",
        "secondary": "#506600",
        "surface-container-highest": "#e0e3e5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "margin": "3rem",
        "gutter": "1.5rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "display-hero-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "label-lg": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
